config/routes.rb
ExpenseManager::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"
  resources :users ,:only => [:show] do
    collection do
    	post :search
    end
  end
  resources :transactions
  resources :group_members
  resources :groups

end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base

  belongs_to :group, counter_cache: true
  belongs_to :user

  validates :group_id, :presence => true, on: :update
  validates :user_id, :presence => true

end

app/controllers/group_members_controller.rb
class GroupMembersController < ApplicationController
  # GET /group_members
  # GET /group_members.json
  def index
    @group_members = GroupMember.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @group_members }
    end
  end

  # GET /group_members/1
  # GET /group_members/1.json
  def show
    @group_member = GroupMember.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group_member }
    end
  end

  # GET /group_members/new
  # GET /group_members/new.json
  def new
    @group_member = GroupMember.new
    @group_member.group_id = params[:group_id]
    render :layout => false
  end

  # GET /group_members/1/edit
  def edit
    @group_member = GroupMember.find(params[:id])
  end

  # POST /group_members
  # POST /group_members.json
  def create
    @group_member = GroupMember.new(group_member_params(params))    
    if(@group_member.save)
      render json { head :no_content }
    else
      render json: {  errors: @group_member.errors.full_messages, status: :unprocessable_entity }
    end
  end

  # PUT /group_members/1
  # PUT /group_members/1.json
  def update
    @group_member = GroupMember.find(params[:id])

    respond_to do |format|
      if @group_member.update_attributes(params[:group_member])
        format.html { redirect_to @group_member, notice: 'Group member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: { errors: @group_member.errors, status: :unprocessable_entity }}
      end
    end
  end

  # DELETE /group_members/1
  # DELETE /group_members/1.json
  def destroy
    @group_member = GroupMember.find(params[:id])
    @group_member.destroy

    respond_to do |format|
      format.html { redirect_to group_members_url }
      format.json { head :no_content }
    end
  end

  def group_member_params(group_member_params)
    group_member_params[:group_member].permit(:group_id,:user_id)
  end

end

app/views/group_members/edit.html.erb
<h1>Editing group_member</h1>

<%= form_for(@group_member  , :remote => true) do |f| %>
  <% if @group_member.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@group_member.errors.count, "error") %> prohibited this group_member from being saved:</h3>

      <ul>
      <% @group_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :group_id %>
    <%= f.label "User name or Email id" %><br />
    <%= text_field_tag :user_email %>
  </div>
  <div class="actions" style="margin: 20px 0px 0px -1px">
    <%= f.submit "Add" %>
  </div>
<% end %>

<%= link_to 'Show', @group_member %> |
<%= link_to 'Back', group_members_path %>

app/views/group_members/index.html.erb
<h1>Listing group_members</h1>

<table>
  <tr>
    <th>Group</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @group_members.each do |group_member| %>
  <tr>
    <td><%= group_member.group_id %></td>
    <td><%= group_member.user_id %></td>
    <td><%= link_to 'Show', group_member %></td>
    <td><%= link_to 'Edit', edit_group_member_path(group_member) %></td>
    <td><%= link_to 'Destroy', group_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group member', new_group_member_path %>

app/views/group_members/new.html.erb
<%= form_for(@group_member  , :remote => true) do |f| %>
  <% if @group_member.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@group_member.errors.count, "error") %> prohibited this group_member from being saved:</h3>

      <ul>
      <% @group_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :group_id %>
    <input id="typeahead-input" type="text" data-provide="typeahead" />
    <%= f.hidden_field :user_id %>
  </div>
  <div class="actions" style="margin: 20px 0px 0px -1px">
    <%= f.submit "Add" %>
  </div>
<% end %>


<br/>

app/views/group_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group:</b>
  <%= @group_member.group_id %>
</p>

<p>
  <b>User:</b>
  <%= @group_member.user_id %>
</p>


<%= link_to 'Edit', edit_group_member_path(@group_member) %> |
<%= link_to 'Back', group_members_path %>