config/routes.rb
ExpenseManager::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"
  resources :users ,:only => [:show] do
    collection do
    	post :search
    end
  end
  resources :transactions
  resources :group_members
  resources :groups

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }

  has_many :group_members

  has_many :transactions

  belongs_to :user

  before_validation :add_creator_as_member, :if => Proc.new {|obj| obj.new_record?}
  
  accepts_nested_attributes_for :group_members, :reject_if => :all_blank


  def add_creator_as_member
  	group_member = GroupMember.new
    group_member.group_id = self.id
    group_member.user_id = self.user_id
    self.group_members << group_member
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @total_paid_owed = Transaction.total_owed_paid.where(["transactions.group_id = ? and 
       transactions.transaction_type = ?",@group.id, Transaction::TRANSACTION_EXPENSE_TYPE]).first
    @members_count = @group.group_members.count
    @total_paid = Transaction.total_payment(@group.id, current_user.id).first
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new
    @group.group_members.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params(params))
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private

  def group_params(group_params)
    group_params = group_params[:group].permit(:name, group_members_attributes: [:user_id])
    group_params["group_members_attributes"].delete_if{|key,value| value["user_id"].blank?}
    group_params
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |group| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"  style="width:200px">
    <%= group.label :name %><br />
    <%= group.text_field :name, {class: 'form-control'}%>
  </div>
  <%= group.fields_for(:group_members) do |member| %>
    <div id ="members" class="field" style="width:200px">
      <%= member.hidden_field :user_id %>
      <%= member.label "Add member" %><br />
      <%= text_field_tag :user_email, '',  {placeholder: 'User name or Email id', class: 'left form-control'} %>
    </div>
    <div style="padding-left: 20px;  float: left;">
      <input id="addMember" value="Add member " class='btn btn-primary ' style='width: 110px;' />
    </div>
  <% end %>
  <div class="separator">&nbsp;</div>
  <div class="actions">
    <%= group.submit 'Create', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<section id="services">
  <div class="container">
    <div class="row">
      <h3>Listing groups</h3>

      <table cellspacing="0" cellpadding="10" class="group_list">
        <tr>
          <th>Name</th>
          <th></th>
        </tr>

      <% @groups.each do |group| %>
        <tr>
          <td><%= group.name %></td>
          <td><%= link_to 'Show', group %> &nbsp;&nbsp;
            <%= link_to 'Edit', edit_group_path(group) %> &nbsp;&nbsp; 
            <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </table>

      <br />

      <%= link_to 'New Group', new_group_path %>
    </div>
  </div>
</section>

app/views/groups/new.html.erb
<section id="services">
  <div class="container">
    <div class="row">
	  <h3>New group</h1>
      <%= render 'form' %>
   </div>
  </div>
</section>

app/views/groups/show.html.erb
<section id="services">
  <div class="container">
    <div class="row">
      <div  class="">
        <ul class='sub-menu tabs' style="margin-top:-10px;style="border-bottom: 1px solid #DFDFDF"">


          <% if @group.present? %>

          <li><%= link_to "members",{ controller: "group_members", :action => "index" } %> </li>
          <li><%= link_to "Expense",{ controller: "transactions", :action =>"new", :group_id => @group.id,  :transaction_type =>Transaction::TRANSACTION_EXPENSE_TYPE }, {:class =>"dialog_link" , :title => "Expense"}%> </li>

          <li><%= link_to "Payment",{ controller: "transactions", :action =>"new", :group_id => @group.id, :transaction_type =>Transaction::TRANSACTION_PAYMENT_TYPE }, {:class =>"dialog_link", :title => "Payment" }%> </li>

          <% end %>
        </ul>

        <div id="total_expense_payment">
          <table style="width:600px">
            <tr>
              <td>
                <div> Total Expense:</div>
                <div> <% total_expense = @total_paid_owed.present? ? @total_paid_owed.total/@members_count : 0  %>
                  <%= total_expense %>
                </div>
              </td>
              <td>
                <div> Total paid:</div>
                <div> <% total_paid = @total_paid.present? ?  @total_paid.total : 0 %>
                  <%= total_paid %>
                </div>
              </td>
              <td>
                <div> Remaining balance to be paid: </div>
                <div> <%= total_expense - total_paid  %> </div>
              </td>
            </tr>
          </tr>
         </table>

        </div>
        <div id="tab-data" style="border-top: 1px solid #DFDFDF">
        <h3>Members of <%= @group.name %></h3>

        <table>
          <tr>
            <th style="text-align:left">User</th>
            <th style="text-align:left">Action</th>
          </tr>

          <% @group.group_members.each do |group_member| %>
          <tr>
            <td style="width: 200px"><%= group_member.user.name %></td>
            <td><%= link_to 'Remove', group_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </table>

        <br />
        <div id="grp_members">

        </div>
        <li><%= link_to "Add member",{:controller => "group_members" , :action =>"new" , :group_id => @group.id}, {:class =>"dialog_link" , :title => "Add Member"}%> </li>

        </div>

      </div>
    </div>

  </div>
</section>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>