config/routes.rb
ExpenseManager::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"
  resources :users ,:only => [:show] do
    collection do
    	post :search
    end
  end
  resources :transactions
  resources :group_members
  resources :groups

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    @transactions = Transaction.all   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @transaction }
    end
  end

  def new
    @transaction = Transaction.new
    @transaction.group_id = params[:group_id]
    @transaction.transaction_type = params[:transaction_type]
    render :layout => false
  end

  def create
    @transaction = Transaction.new(transaction_params(params))
    @transaction.paid_by = current_user.id
    @success = false
    if @transaction.save
      @msg = get_save_msg
      @success = true
      render json: { status: :ok , msg: @msg}
    else      
      @error = @transaction.errors.messages
      render json: { status: :internal_server_error , msg: @msg}
    end    
  end

  private
  def transaction_params(params)
    params.require(:transaction).permit(:amount, :description, :transaction_type, :user_id, :group_id)
  end

  def get_save_msg
    if @transaction.transaction_type == Transaction::TRANSACTION_PAYMENT_TYPE
      return "Payment to #{@transaction.user.name} succcefully done."
    else
      return "Expense recorded succcefully ."
    end
  end
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction , :remote => true) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :group_id %>
  <%= f.hidden_field :transaction_type %>
  <% if params[:transaction_type] == Transaction::TRANSACTION_PAYMENT_TYPE %>
   
    <div class="field">
      <%= f.label :user %><br />
      <select name="payed_to">
        <option value=""> Select user</option>
        <% @transaction.group.group_members.each do |member| %> 
            <option value="<%= member.user_id %>"> <%=  member.user.name %></option>
        <% end %>
      </select>

    </div>
    <div class="field">
      <%= f.label :amount %><br />
      <%= f.number_field :amount %>
    </div>
   <% else %>
    <div class="field">
      <%= f.label :amount %><br />
      <%= f.number_field :amount %>
    </div>
     <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description ,:rows => 3 %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Transaction type</th>
    <th>Description</th>
    <th>User</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.transaction_type %></td>
    <td><%= transaction.description %></td>
    <td><%= transaction.user_id %></td>
    <td><%= transaction.amount %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h3>New transaction</h3>

<%= render 'form' %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Transaction type:</b>
  <%= @transaction.transaction_type %>
</p>

<p>
  <b>Description:</b>
  <%= @transaction.description %>
</p>

<p>
  <b>User:</b>
  <%= @transaction.user_id %>
</p>

<p>
  <b>Amount:</b>
  <%= @transaction.amount %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>